# Generated by Django 2.0 on 2018-03-05 22:21

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waffle', '0002_auto_20161201_0958'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sample',
            options={'verbose_name': 'Sample', 'verbose_name_plural': 'Samples'},
        ),
        migrations.AlterModelOptions(
            name='switch',
            options={'verbose_name': 'Switch', 'verbose_name_plural': 'Switches'},
        ),
        migrations.AlterField(
            model_name='sample',
            name='created',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Date when this Sample was created.', verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='modified',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date when this Sample was last modified.', verbose_name='Modified'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='name',
            field=models.CharField(help_text='The human/computer readable name.', max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='note',
            field=models.TextField(blank=True, help_text='Note where this Sample is used.', verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='percent',
            field=models.DecimalField(decimal_places=1, help_text='A number between 0.0 and 100.0 to indicate a percentage of the time this sample will be active.', max_digits=4, verbose_name='Percent'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='active',
            field=models.BooleanField(default=False, help_text='Is this switch active?', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='created',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Date when this Switch was created.', verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='modified',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date when this Switch was last modified.', verbose_name='Modified'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='name',
            field=models.CharField(help_text='The human/computer readable name.', max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='note',
            field=models.TextField(blank=True, help_text='Note where this Switch is used.', verbose_name='Note'),
        ),
    ]
