# Generated by Django 3.2.7 on 2022-01-21 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("waffle", "0003_update_strings_for_i18n"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Flag",
        ),
    ]
