# Generated by Django 3.0.2 on 2020-01-16 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waffle', '0003_update_strings_for_i18n'),
    ]

    operations = [
        migrations.AddField(
            model_name='flag',
            name='category',
            field=models.CharField(blank=True, help_text='Category label used to filter flags.', max_length=100, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='switch',
            name='category',
            field=models.CharField(blank=True, help_text='Category label used to filter switches.', max_length=100, verbose_name='Category'),
        ),
    ]
